version: '3.9'
# compose name
# name: docker-compose-learning

services:
  app:
    container_name: go-app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
      # - name=value
    build:
      context: ./go_sample_postgres/
      dockerfile: Dockerfile
    depends_on:
      postgresdb:
        condition: service_healthy
    ports:
      - 5555:78
    networks:
      - net_mycompose_niswatunsa18

  postgresdb:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_NAME=${DB_NAME}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - vol_mycompose_niswatunsa18:/var/lib/postgres/data
    networks:
      - net_mycompose_niswatunsa18

volumes:
  vol_mycompose_niswatunsa18:
  
networks:
  net_mycompose_niswatunsa18:
    driver: bridge