version: '3.9'
# compose name
# name: docker-compose-learning

services:
  app:
    container_name: go-app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
      # - name=value
    build:
      context: ./go_sample_postgres/
      dockerfile: Dockerfile
    depends_on:
      postgresdb:
        condition: service_healthy
    ports:
      - 9911:78
    networks:
      - netwwc

  postgresdb:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5431:5432'
    volumes:
      - volwwc:/var/lib/postgres/data
    networks:
      - netwwc

volumes:
  volwwc:
networks:
  netwwc:
    driver: bridge